### ISSUE TITLE
메뉴얼에 오타가 있음

### ISSUE THREAD

**Issue by smaker** [xpressengine/xpressengine-manual#10]
![screenshot-www xpressengine io-2019 05 10-12-53-22](https://user-images.githubusercontent.com/1732040/57501496-b6889f00-7322-11e9-8293-79dd32b91884.png)

괄호를 닫지 않아서, 그대로 코드를 복사하면 사진과 같은 오류가 발생합니다.

https://www.xpressengine.io/guide/plugin-make-guide/admin-site-menu-extend

**Comment by icetea-0224** [comment]
https://github.com/xpressengine/xpressengine-manual/commit/0a0adf91f9d476f4b70a9f74e51a3b2930be13c9

에서 처리하였습니다.
감사합니다.
