### ISSUE TITLE
gitbook 에서 매뉴얼을 볼 수 없습니다!

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine-manual#4]
gitbook 에서 매뉴얼 보면서 했는데 ㅠㅠ 이제는 보이지가 않고, 깃허브에서 직접봐야합니다 ㅠㅠ
확인부탁드립니다

**Comment by ghost** [comment]
@Laeng gitbook의 시스템 변경으로 주소가 약간 변경되었습니다.

https://xpressengine.gitbook.io/xpressengine-manual/summary

이 주소에서 보실 수 있으며, 공식사이트 링크는 이미 변경되어 있으므로 주소 변경 시 공식사이트의 메뉴에서 확인해주세요.

**Comment by Laeng** [comment]
아하! ㅠㅠ 고맙습니다!
