### ISSUE TITLE
설치하기 문서 업데이트에 대한 요청

### ISSUE THREAD

**Issue by Laeng** [xpressengine/xpressengine-manual#5]
닷홈 무제한 웹호스팅에서 composer 를 사용할 수 없다고 합니다.
https://www.xpressengine.io/qna/%EC%95%88%EB%85%95%ED%95%98%EC%84%B8%EC%9A%94-%EB%8B%B7%ED%99%88-xe3-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98-%EC%8B%9C-%EC%97%90%EB%9F%AC-%EB%AC%B8%EC%9D%98-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4

web-installer 폴더가 첨부된 lasted.zip 파일안에 없어 웹인스톨을 할 수 없습니다.
https://www.xpressengine.io/qna/%EC%8B%9C%EB%86%80%EB%A1%9C%EC%A7%80-%EC%9B%B9%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%85%98%EC%97%90-%EC%84%A4%EC%B9%98%ED%95%98%EB%A0%A4%EB%A9%B4-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C%EC%9A%94

**Comment by icetea-0224** [comment]
안녕하세요,
늦게 이슈에 대한 코멘트를 작성하게 되어 대단히 죄송합니다.

해당 이슈는 저희가 차근차근 확인한 후 신중하게 가이드할 수 있도록 하고 있으며, 2019년 4월 9일일자로 갱신된 가이드 지침을 따라 설치 부탁드립니다.

항상 감사드립니다.
